name: Terraform Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.6 # Use your required Terraform version

    - name: Initialize Terraform
      run: terraform init

    - name: Validate Terraform
      run: terraform validate

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan

    # - name: Comment Plan Output
    #   if: ${{ github.event_name == 'pull_request' }}
    #   run: |
    #     echo "#### Terraform Plan Output" > plan_output.md
    #     terraform-bin show -json tfplan | jq '.' >> plan_output.md
    #     gh pr comment --body-file plan_output.md

    - name: Terraform Apply
      if: ${{ github.event_name == 'push' }}
      run: terraform apply -auto-approve tfplan

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #AWS_DEFAULT_REGION: us-east-1 # Adjust to your region
      GH_TOKEN: ${{ github.token }}
